[package]
name = "salusd"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
interprocess = { workspace = true }
libsalus = { path = "../libsalus" }
tokio = { workspace = true }
