[package]
name = "libsalus"
version = "0.1.0"
edition = "2024"

[features]
unstable = []

[dependencies]
anyhow = { workspace = true }
aws-lc-rs = "1.14.0"
bincode = { workspace = true }
bon = { workspace = true }
ssss = "1.0.2"
tracing = { workspace = true }

[build-dependencies]
rustversion = { workspace = true }

[dev-dependencies]
rand = "0.9.2"
