[package]
name = "salus"
version = "0.1.0"
edition = "2024"

[features]
unstable = []

[dependencies]
anyhow = { workspace = true }
clap = { version = "4.5.47", features = ["derive"] }
config = "0.15.15"
interprocess = { workspace = true }
libsalus = { path = "../libsalus" }
tokio = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
rustversion = { workspace = true }
