on:
  push:
    branches:
      - master
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - "*"
  schedule:
    - cron: "27 4 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

name: 🔐 salus 🔐

jobs:
  rustfmt:
    name: 📌 Formatting 📌
    # main
    uses: rustyhorde/workflows/.github/workflows/rustfmt.yml@8e51586c8533d90c84d23cd9ac94ec2e3eb7afc1
    secrets: inherit

  lints-linux:
    name: 🕳️ Clippy (Linux) 🕳️
    needs: rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: ✅ Checkout ✅
        uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49 # v3.8.0
        with:
          action: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
          attempt_limit: 3
          attempt_delay: 30000
      - name: 🧹 Cleanup 🧹
        run: |
          rm -rf /home/runner/.cargo/bin/rustfmt
          rm -rf /home/runner/.cargo/bin/cargo-fmt
          rm -rf /home/runner/.cargo/bin/rust-analyzer
      - name: 🧰 Toolchain 🧰
        run: |
          rustup toolchain remove nightly
          rustup toolchain install nightly --profile default --no-self-update
          rustup default nightly
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: x86_64-unknown-linux-gnu
          cache-all-crates: true
      - name: 💾 Install (cargo-binstall) 💾
        uses: cargo-bins/cargo-binstall@1c2b96c2b86875d56caeec7b7ee9980812daf0d9 # main
      - name: 💾 Install (cargo-matrix) 💾
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          cargo binstall --no-confirm --no-symlinks --no-discover-github-token cargo-matrix --force
          rustup override remove
      - name: 📎 Clippy 📎
        run: cargo matrix --channel linux clippy --all-targets -- -Dwarnings

  lints-macos:
    name: 🕳️ Clippy (MacOS) 🕳️
    needs: rustfmt
    runs-on: macos-latest
    steps:
      - name: ✅ Checkout ✅
        uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49 # v3.8.0
        with:
          action: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
          attempt_limit: 3
          attempt_delay: 30000
      - name: 🧰 Toolchain 🧰
        run: |
          rustup toolchain remove nightly
          rustup toolchain install nightly --profile default --no-self-update
          rustup default nightly
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: apple-darwin
          cache-all-crates: true
      - name: 💾 Install (cargo-binstall) 💾
        uses: cargo-bins/cargo-binstall@1c2b96c2b86875d56caeec7b7ee9980812daf0d9 # main
      - name: 💾 Install (cargo-matrix) 💾
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          cargo binstall --no-confirm --no-symlinks --no-discover-github-token cargo-matrix --force
          rustup override remove
      - name: 📎 Clippy 📎
        run: cargo matrix --channel macos clippy --all-targets -- -Dwarnings

  test-linux:
    name: 🧪 Test (Linux) 🧪
    needs: lints-linux
    strategy:
      matrix:
        os: [ubuntu-latest]
        channel: ["1.91.1", "stable", "beta", "nightly"]
        target: [x86_64-unknown-linux-gnu]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ✅ Checkout ✅
        uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49 # v3.8.0
        with:
          action: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
          attempt_limit: 3
          attempt_delay: 30000
      - name: 🧹 Cleanup 🧹
        run: |
          rm -rf /home/runner/.cargo/bin/rustfmt
          rm -rf /home/runner/.cargo/bin/cargo-fmt
          rm -rf /home/runner/.cargo/bin/rust-analyzer
      - name: 🧰 Toolchain 🧰
        run: |
          rustup toolchain remove ${{ matrix.channel }}-${{ matrix.target }}
          rustup toolchain install ${{ matrix.channel }}-${{ matrix.target }} --profile minimal --no-self-update
          rustup default ${{ matrix.channel }}
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: ${{ matrix.target }}
          cache-all-crates: true
      - name: 💾 Install (cargo-binstall) 💾
        uses: cargo-bins/cargo-binstall@1c2b96c2b86875d56caeec7b7ee9980812daf0d9 # main
      - name: 💾 Install (cargo-matrix) 💾
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          cargo binstall --no-confirm --no-symlinks --no-discover-github-token cargo-matrix --force
          rustup override remove
      - name: 🧪 Test 🧪
        run: cargo matrix --channel linux test

  test-macos:
    name: 🧪 Test (MacOS) 🧪
    needs: lints-macos
    strategy:
      matrix:
        os: [macos-latest]
        channel: ["1.91.1", "stable", "beta", "nightly"]
        target: [apple-darwin]
    runs-on: ${{ matrix.os }}
    steps:
      - name: ✅ Checkout ✅
        uses: Wandalen/wretry.action@71a909ebf09f3ffdc6f42a17bd54ecb43481da49 # v3.8.0
        with:
          action: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
          attempt_limit: 3
          attempt_delay: 30000
      - name: 🧰 Toolchain 🧰
        run: |
          rustup toolchain remove ${{ matrix.channel }}-${{ matrix.target }}
          rustup toolchain install ${{ matrix.channel }}-${{ matrix.target }} --profile minimal --no-self-update
          rustup default ${{ matrix.channel }}
      - name: 💵 Rust Cache 💵
        uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        if: ${{ github.event_name != 'pull_request' || ! github.event.pull_request.head.repo.fork }}
        with:
          key: ${{ matrix.target }}
          cache-all-crates: true
      - name: 💾 Install (cargo-binstall) 💾
        uses: cargo-bins/cargo-binstall@1c2b96c2b86875d56caeec7b7ee9980812daf0d9 # main
      - name: 💾 Install (cargo-matrix) 💾
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          cargo binstall --no-confirm --no-symlinks --no-discover-github-token cargo-matrix --force
          rustup override remove
      - name: 🧪 Test 🧪
        run: cargo matrix --channel macos test

  coverage-linux:
    name: 🧱 Coverage (Linux) 🧱
    needs: test-linux
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@8e51586c8533d90c84d23cd9ac94ec2e3eb7afc1
    with:
      os: ubuntu-latest
      channel: nightly
      target: x86_64-unknown-linux-gnu
      lcov: true
      html: true
      run_cmd: ${{ vars.COVERAGE_RUN_CMD }}
    secrets: inherit

  coverage-macos:
    name: 🧱 Coverage (MacOS) 🧱
    needs: test-macos
    # main
    uses: rustyhorde/workflows/.github/workflows/coverage.yml@8e51586c8533d90c84d23cd9ac94ec2e3eb7afc1
    with:
      os: macos-latest
      channel: nightly
      target: apple-darwin
      lcov: true
      html: true
      run_cmd: ${{ vars.COVERAGE_RUN_CMD }}
    secrets: inherit
